'use strict';

const testcases = [
    "Take a breath, now. Take another. Feel air in your lungs. Let your limbs return. Yes, move your fingers. Have a body again, under gravity, in air. Respawn in the long dream. There you are. Your body touching the universe again at every point, as though you were separate things. As though we were separate things.",
    "Who are we? Once we were called the spirit of the mountain. Father sun, mother moon. Ancestral spirits, animal spirits. Jinn. Ghosts. The green man. Then gods, demons. Angels. Poltergeists. Aliens, extraterrestrials. Leptons, quarks. The words change. We do not change.",
    "We are the universe. We are everything you think isn't you. You are looking at us now, through your skin and your eyes. And why does the universe touch your skin, and throw light on you? To see you, player. To know you. And to be known. I shall tell you a story.",
    "Sometimes it thought itself human, on the thin crust of a spinning globe of molten rock. The ball of molten rock circled a ball of blazing gas that was three hundred and thirty thousand times more massive than it. They were so far apart that light took eight minutes to cross the gap. The light was information from a star, and it could burn your skin from a hundred and fifty million kilometres away.",
    "Sometimes the player dreamed it was a miner, on the surface of a world that was flat, and infinite. The sun was a square of white. The days were short; there was much to do; and death was a temporary inconvenience.",
    "Sometimes the player dreamed it was other things, in other places. Sometimes these dreams were disturbing. Sometimes very beautiful indeed. Sometimes the player woke from one dream into another, then woke from that into a third.",
    "The atoms of the player were scattered in the grass, in the rivers, in the air, in the ground. A woman gathered the atoms; she drank and ate and inhaled; and the woman assembled the player, in her body. And the player awoke, from the warm, dark world of its mother's body, into the long dream.",
    "And the player was a new story, never told before, written in letters of DNA. And the player was a new program, never run before, generated by a sourcecode a billion years old. And the player was a new human, never alive before, made from nothing but milk and love.",
    "The seven billion billion billion atoms of the player's body were created, long before this game, in the heart of a star. So the player, too, is information from a star. And the player moves through a story, which is a forest of information planted by a man called Julian, on a flat, infinite world created by a man called Markus, that exists inside a small, private world created by the player, who inhabits a universe created by.",
    "Shush. Sometimes the player created a small, private world that was soft and warm and simple. Sometimes hard, and cold, and complicated. Sometimes it built a model of the universe in its head; flecks of energy, moving through vast empty spaces. Sometimes it called those flecks \"electrons\" and \"protons\". Sometimes it called them \"planets\" and \"stars\".",
    "And sometimes the player believed the universe had spoken to it through the light that fell from the crisp night sky of winter, where a fleck of light in the corner of the player's eye might be a star a million times as massive as the sun, boiling its planets to plasma in order to be visible for a moment to the player, walking home at the far side of the universe, suddenly smelling food, almost at the familiar door, about to dream again."
];

let testcaseIndex = -1;
let startTime = 0;
let completeWords = [];
let pendingWords = [];
let typingword = '';
let completePart = '';
let pendingPart = '';
let totalWords = 0;
let gameRunning = false;



function ResetStatus() {
    gameRunning = false;
    let tcase = testcases[testcaseIndex];
    pendingWords = tcase.split(' ');
    totalWords = pendingWords.length;
    typingword = pendingPart = pendingWords[0];
    pendingWords.splice(0, 1);
    
}

function ChangeTestcase() {
    testcaseIndex = Math.floor(Math.random() * testcases.length);
    ResetStatus();
    
}

function RollWord() {
    completeWords.push(typingword);
    typingword = pendingPart = pendingWords[0];
    pendingWords.splice(0, 1);
    document.querySelector('#input-word').value = '';
}

function StartGame() {
    gameRunning = true;
    startTime = Date.now();
}

function Render() {
    document.querySelector('#sentence-done').innerText = completeWords.join(' ');
    document.querySelector("#word-done").innerText = completePart;
    document.querySelector("#word-pending").innerText = pendingPart;
    document.querySelector("#sentence-pending").innerText = pendingWords.join(' ');
}

window.addEventListener('load', function() {
    document.querySelector('#live-input-card').addEventListener('click', () => {
        document.querySelector('#input-word').focus();
    });

    this.document.querySelector('#input-word').addEventListener('keyup', e => {
        if (e.key === ' ') {
            // press space bar, go to next word
            
        } else if (e.key === 'Backspace') {
            // go back a letter
        } else {

        }


        
    });

    ChangeTestcase();
    Render();
});